export const CLI_NATIVE_PARITY: Record<string, string> = Object.freeze({
  memorix_store: 'memorix memory store',
  memorix_search: 'memorix memory search',
  memorix_detail: 'memorix memory detail',
  memorix_graph_context: 'memorix memory graph-context',
  memorix_project_context: 'memorix context|resume',
  memorix_context_pack: 'memorix codegraph context-pack',
  memorix_compaction_checkpoint: 'memorix checkpoint list|show|context|archive',
  memorix_codegraph_status: 'memorix codegraph status',
  memorix_knowledge: 'memorix knowledge init|status|compile|lint|apply|workflow',
  memorix_resolve: 'memorix memory resolve',
  memorix_timeline: 'memorix memory timeline',
  memorix_suggest_topic_key: 'memorix memory suggest-topic-key',
  memorix_session_start: 'memorix session start',
  memorix_session_end: 'memorix session end',
  memorix_session_context: 'memorix session context',
  memorix_store_reasoning: 'memorix reasoning store',
  memorix_search_reasoning: 'memorix reasoning search',
  memorix_transfer: 'memorix transfer export|import',
  memorix_retention: 'memorix retention status|archive|stale',
  memorix_media: 'memorix media import|attach|list|show|generate|status',
  memorix_dashboard: 'memorix dashboard',
  memorix_handoff: 'memorix handoff send',
  memorix_poll: 'memorix poll',
  team_manage: 'memorix team join|leave|roles|add-role|remove-role|status',
  team_message: 'memorix message send|broadcast|inbox',
  team_task: 'memorix task create|claim|complete|fail|release|list',
  team_file_lock: 'memorix lock lock|unlock|status',
  memorix_audit_project: 'memorix audit project',
  memorix_deduplicate: 'memorix memory deduplicate',
  memorix_consolidate: 'memorix memory consolidate',
  memorix_formation_metrics: 'memorix formation metrics',
  memorix_skills: 'memorix skills list|generate|show',
  memorix_promote: 'memorix memory promote',
  memorix_rules_sync: 'memorix sync rules',
  memorix_workspace_sync: 'memorix sync workspace',
  memorix_ingest_image: 'memorix ingest image',
});

export const MCP_ONLY_COMPATIBILITY_TOOLS = Object.freeze([
  'create_entities',
  'create_relations',
  'add_observations',
  'delete_entities',
  'delete_observations',
  'delete_relations',
  'read_graph',
  'search_nodes',
  'open_nodes',
]);
